name: Rcaas CI
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Rcaas Api Docker image
      run: docker build rcaas-api --file rcaas-api/Dockerfile --tag ${{ secrets.DOCKER_REGISTRY }}/rcaas-api
    - name: Build the Rcaas UI Docker image
      run: docker build rcaas-ui --file rcaas-ui/Dockerfile --tag ${{ secrets.DOCKER_REGISTRY }}/rcaas-ui
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push Rcaas Api image
      run: docker push ${{ secrets.DOCKER_REGISTRY }}/rcaas-api
    - name: Push Rcaas UI images
      run: docker push ${{ secrets.DOCKER_REGISTRY }}/rcaas-ui
    - name: update Rcaas Api container with new image version
      run: | 
        curl \
        --request POST \
        --header "X-Auth-Token: ${{ secrets.DOCKER_TOKEN }}" \
        "https://api.scaleway.com/containers/v1beta1/regions/nl-ams/containers/29a7fd74-c1d8-4290-a7f7-01554bee7cf7/deploy" \
        -d "{}"
    - name: update Rcaas UI container with new image version
      run: | 
        curl \
        --request POST \
        --header "X-Auth-Token: ${{ secrets.DOCKER_TOKEN }}" \
        "https://api.scaleway.com/containers/v1beta1/regions/nl-ams/containers/f6fc8e6a-8367-4693-8822-3b9a9c26f9e3/deploy" \
        -d "{}"
