name: Rcaas UI Pipeline
on:
  push:
    branches: [ "master" ]
    paths:
      - rcaas-ui/**
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build rcaas-ui --file rcaas-ui/Dockerfile --tag ${{ secrets.DOCKER_REGISTRY }}/rcaas-ui
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker Push Image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/rcaas-ui
  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve container id
        run: |
          container_id=`curl -s \
            --request GET \
            --header "X-Auth-Token: ${{ secrets.DOCKER_TOKEN }}" \
            "https://api.scaleway.com/containers/v1beta1/regions/nl-ams/containers" \
            -d "{}" | jq -r '.containers[] | select(.name=="rcaas-ui") | .id'`
      - name: Deploy container with new image version
        run: |
          curl \
          --request POST \
          --header "X-Auth-Token: ${{ secrets.DOCKER_TOKEN }}" \
          "https://api.scaleway.com/containers/v1beta1/regions/nl-ams/containers/$container_id/deploy" \
          -d "{}" -v
